### ISSUE TITLE
Error when running the example 

### ISSUE THREAD

**Issue by JUREXT** [PrinsFrank/php-geo-svg#8]
I tried  to run this example.

https://github.com/PrinsFrank/php-geo-svg#from-a-geojson-array

Problem: 

Parse error: syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in C:......vendor\prinsfrank\php-geo-svg\src\GeoSVG.php on line 24

**Comment by PrinsFrank** [comment]
Hi @JUREXT , I'm glad to help!

It looks like you are running an older PHP version. [Line 24 in release 0.0.1 contains the property ```private ?Scale $scale = null;```](https://github.com/PrinsFrank/php-geo-svg/blame/efbcec830e87eb54aac852fff0a0aa3926788c36/src/GeoSVG.php#L24), which is a typed property, only supported since PHP 7.4.

This package is built for PHP 8.0 and 8.1, [since older versions don't have active support anymore](https://www.php.net/supported-versions.php). You were able to download an older version of this package with composer (v0.0.1) and not the more recent 0.0.2 because the [first release doesn't have supported php version specified](https://packagist.org/packages/prinsfrank/php-geo-svg#v0.0.1) and the [more recent release does](https://packagist.org/packages/prinsfrank/php-geo-svg#v0.0.2). 

I would suggest you update your php version to a more recent one and try again. As I'm unable to update the php requirements for that old release I'll add PHP requirements to the README. I hope this answers your question, If you have any further questions or remarks please let me know.

**Comment by JUREXT** [comment]
Thanks for the reply.

I checked my PHP version and it is: PHP 7.3.12, after updating to 8.1.0 it now works. Thank you.
